-- ============================================================================
-- MboaTech — Initialisation complète base PostgreSQL (Neon)
-- Fichier unique : schema_updated.sql + migrations 2026_08 non encore intégrées
-- Généré le 2026-09-01
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 1 : Schéma de base (schema_updated.sql — verbatim)
-- ════════════════════════════════════════════════════════════════════════════

-- PostgreSQL schema for MboaTech
-- Converted from MySQL 8.0
--
-- Note : role / availability_status / level sont mappés en Java par
-- @Enumerated(EnumType.STRING) (enums Role / AvailabilityStatus /
-- AttestationLevel). Ils sont donc stockés en VARCHAR + contrainte CHECK :
-- PostgreSQL ne permet pas de comparer implicitement un VARCHAR à un type
-- ENUM natif sous Hibernate. Les autres colonnes « enum » MySQL sont aussi
-- mappées en String Java (VARCHAR + CHECK).

-- ─── Trigger function for updated_at ────────────────────────────────

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── Tables ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  role          VARCHAR(20)  NOT NULL DEFAULT 'client',
  phone         VARCHAR(30)  NULL,
  photo_url     VARCHAR(500) NULL,
  status        VARCHAR(20)  NOT NULL DEFAULT 'active',
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_users_status CHECK (status IN ('active','inactive','pending','suspended')),
  CONSTRAINT chk_users_role   CHECK (role IN ('client','technician','admin'))
);

CREATE TRIGGER set_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS clients (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  city       VARCHAR(120) NULL,
  location   VARCHAR(255) NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER set_clients_updated_at
  BEFORE UPDATE ON clients
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS technicians (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               BIGINT              NOT NULL UNIQUE,
  domain                VARCHAR(150)        NULL,
  city                  VARCHAR(120)        NULL,
  location              VARCHAR(255)        NULL,
  bio                   TEXT                NULL,
  specialties           TEXT                NULL,
  rating_avg            DECIMAL(3,2)        NOT NULL DEFAULT 0.00,
  rating_count          INT                 NOT NULL DEFAULT 0,
  experience_years      SMALLINT            NULL,
  verified              BOOLEAN             NOT NULL DEFAULT FALSE,
  availability_status   VARCHAR(20) NOT NULL DEFAULT 'available',
  hourly_rate           DECIMAL(10,2)       NULL,
  success_rate          DECIMAL(5,2)        NOT NULL DEFAULT 0.00,
  acceptance_count      INT                 NOT NULL DEFAULT 0,
  decline_count         INT                 NOT NULL DEFAULT 0,
  avg_response_time_sec INT                 NOT NULL DEFAULT 0,
  suspended_until       TIMESTAMP           NULL,
  suspended_permanent   BOOLEAN             NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_technician_profiles_availability_status
    CHECK (availability_status IN ('available','busy','offline'))
);

CREATE TRIGGER set_technicians_updated_at
  BEFORE UPDATE ON technicians
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS admins (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  role_name  VARCHAR(50)  NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER set_admins_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS service_requests (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        BIGINT       NOT NULL,
  technician_id    BIGINT       NULL,
  category         VARCHAR(100) NOT NULL,
  description      TEXT         NOT NULL,
  urgency          VARCHAR(20)  NOT NULL DEFAULT 'normal',
  status           VARCHAR(20)  NOT NULL DEFAULT 'published',
  budget_min       DECIMAL(10,2) NULL,
  budget_max       DECIMAL(10,2) NULL,
  address          VARCHAR(255) NULL,
  city             VARCHAR(120) NULL,
  scheduled_at     TIMESTAMP    NULL,
  reserved_until   TIMESTAMP    NULL,
  completed_at     TIMESTAMP    NULL,
  funds_deposited  BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_open     BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_reporter_user_id BIGINT NULL,
  dispute_open_at  TIMESTAMP    NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_service_requests_client     FOREIGN KEY (client_id)     REFERENCES clients (id)     ON DELETE CASCADE,
  CONSTRAINT fk_service_requests_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE SET NULL,
  CONSTRAINT chk_service_requests_urgency CHECK (urgency IN ('normal','important','critique')),
  CONSTRAINT chk_service_requests_status   CHECK (status IN ('draft','published','assigned','in_progress','completed','cancelled','disputed'))
);

CREATE INDEX idx_service_requests_client     ON service_requests (client_id);
CREATE INDEX idx_service_requests_technician ON service_requests (technician_id);

CREATE TRIGGER set_service_requests_updated_at
  BEFORE UPDATE ON service_requests
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS chat_messages (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  sender_user_id     BIGINT       NOT NULL,
  message_text       TEXT         NULL,
  attachment_url     VARCHAR(500) NULL,
  is_read            BOOLEAN      NOT NULL DEFAULT FALSE,
  schedule_at        TIMESTAMP    NULL,
  schedule_status    VARCHAR(20)  NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chat_messages_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_messages_sender  FOREIGN KEY (sender_user_id)     REFERENCES users (id)          ON DELETE CASCADE
);

CREATE INDEX idx_chat_service_request ON chat_messages (service_request_id);
CREATE INDEX idx_chat_sender          ON chat_messages (sender_user_id);

CREATE TABLE IF NOT EXISTS payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT        NOT NULL,
  payer_user_id      BIGINT        NOT NULL,
  payee_user_id      BIGINT        NOT NULL,
  amount             DECIMAL(12,2) NOT NULL,
  currency           VARCHAR(10)   NOT NULL DEFAULT 'XAF',
  status             VARCHAR(20)   NOT NULL DEFAULT 'pending',
  method             VARCHAR(50)   NOT NULL DEFAULT 'momo',
  transaction_ref    VARCHAR(255)  NULL,
  payment_url        VARCHAR(500)  NULL,
  notes              TEXT          NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_payments_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_payer   FOREIGN KEY (payer_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT fk_payments_payee   FOREIGN KEY (payee_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_payments_status CHECK (status IN ('pending','held','released','refunded','failed'))
);

CREATE INDEX idx_payments_request ON payments (service_request_id);

CREATE TRIGGER set_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS technician_recommendations (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id       BIGINT       NOT NULL,
  recommender_user_id BIGINT       NULL,
  recommender_name    VARCHAR(150) NULL,
  comment             TEXT         NULL,
  rating              SMALLINT     NULL,
  verified            BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_recommendations_technician  FOREIGN KEY (technician_id)       REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT fk_recommendations_recommender FOREIGN KEY (recommender_user_id) REFERENCES users (id)      ON DELETE SET NULL
);

CREATE INDEX idx_recommendations_technician ON technician_recommendations (technician_id);

CREATE TABLE IF NOT EXISTS notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  title      VARCHAR(200) NOT NULL,
  message    TEXT         NULL,
  type       VARCHAR(20)  NOT NULL DEFAULT 'system',
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user ON notifications (user_id, is_read);

CREATE TABLE IF NOT EXISTS documents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT       NOT NULL,
  type            VARCHAR(30)  NOT NULL DEFAULT 'other',
  file_url        VARCHAR(500) NOT NULL,
  status          VARCHAR(20)  NOT NULL DEFAULT 'pending',
  review_comments TEXT         NULL,
  uploaded_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
  reviewed_at     TIMESTAMP    NULL,
  CONSTRAINT fk_documents_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_documents_type   CHECK (type   IN ('id_card','recommendation_letter','certification','other')),
  CONSTRAINT chk_documents_status CHECK (status IN ('pending','approved','rejected'))
);

CREATE INDEX idx_documents_user ON documents (user_id);

CREATE TABLE IF NOT EXISTS disputes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  reported_by_user_id BIGINT      NOT NULL,
  description        TEXT         NOT NULL,
  status             VARCHAR(20)  NOT NULL DEFAULT 'open',
  resolution         TEXT         NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  resolved_at        TIMESTAMP    NULL,
  CONSTRAINT fk_disputes_request     FOREIGN KEY (service_request_id)   REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_disputes_reported_by FOREIGN KEY (reported_by_user_id)  REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_disputes_status CHECK (status IN ('open','under_review','resolved','rejected'))
);

CREATE INDEX idx_disputes_request ON disputes (service_request_id);

CREATE TABLE IF NOT EXISTS attestations (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id      BIGINT             NOT NULL,
  intervention_count INT                NOT NULL,
  avg_rating         DECIMAL(3,1)       NOT NULL,
  level              VARCHAR(20)      NOT NULL,
  attestation_number VARCHAR(30)        NOT NULL,
  generated_at       TIMESTAMP          NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_attestation_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT uk_attestation_number     UNIQUE (attestation_number),
  CONSTRAINT chk_attestations_level
    CHECK (level IN ('BRONZE','SILVER','GOLD','DIAMOND'))
);

CREATE INDEX idx_attestation_technician ON attestations (technician_id);

-- ════════════════════════════════════════════════════════════════════════════
-- SECTION 2 : Migrations 2026_08 — tables/colonnes non encore présentes
--
-- Les migrations suivantes ont été EXCLUES car leurs objets existent déjà
-- dans schema_updated.sql :
--   add_attestations        → table attestations déjà créée (VARCHAR+CHECK)
--   add_chat_dispute        → colonnes funds_deposited, dispute_open déjà dans service_requests
--   add_chat_read           → colonne is_read déjà dans chat_messages
--   add_chat_schedule       → colonnes schedule_at, schedule_status déjà dans chat_messages
--   add_client_withdrawals  → no-op conditionnel sur base neuve (table absente)
--   add_dispute_reporter    → colonnes dispute_reporter_user_id, dispute_open_at déjà dans service_requests
--   add_notifications       → table notifications déjà créée
--   add_payment_url         → colonne payment_url déjà dans payments
--   add_rating              → colonne rating déjà dans technician_recommendations
--   add_reservation_guards  → colonnes reserved_until, acceptance_count, decline_count déjà présentes
--   add_suspensions         → colonnes reason, suspended_until, suspended_permanent déjà présentes
--   add_user_photo          → colonne photo_url déjà dans users
--   dispute_payment_method  → colonne method déjà VARCHAR(50) dans payments
--
-- migration_2026_09_enum_to_varchar.sql : OBSOLÈTE (schema_updated.sql utilise déjà VARCHAR+CHECK)
-- ════════════════════════════════════════════════════════════════════════════


-- ─── Migration : sessions d'authentification persistantes ───────────────────
-- Table : auth_sessions (pas dans schema_updated.sql)
-- Note : expires_at est déjà inclus dans la définition ci-dessous.
--        add_auth_sessions_expiry est donc couvert en une seule création.

CREATE TABLE IF NOT EXISTS auth_sessions (
  token      VARCHAR(64) NOT NULL PRIMARY KEY,
  username   VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL DEFAULT (NOW() + INTERVAL '30 days')
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_username ON auth_sessions (username);


-- ─── Migration : documents KYC ─────────────────────────────────────────────
-- Table : kyc_documents (pas dans schema_updated.sql)
-- À ne pas confondre avec la table « documents » qui stocke les documents
-- des techniciens (CNI, certifications, lettres de recommandation).

CREATE TABLE IF NOT EXISTS kyc_documents (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  doc_type   VARCHAR(50)  NOT NULL,
  file_url   VARCHAR(500) NOT NULL,
  status     VARCHAR(20)  NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_kyc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kyc_user ON kyc_documents (user_id);


-- ─── Migration : réglages globaux de la plateforme ──────────────────────────
-- Table : platform_settings (pas dans schema_updated.sql)

CREATE TABLE IF NOT EXISTS platform_settings (
  setting_key   VARCHAR(64) NOT NULL PRIMARY KEY,
  setting_value VARCHAR(255) NOT NULL DEFAULT '',
  updated_at    TIMESTAMP   NOT NULL DEFAULT NOW()
);

INSERT INTO platform_settings (setting_key, setting_value)
VALUES ('payments_enabled', 'true')
ON CONFLICT (setting_key) DO NOTHING;


-- ─── Migration : portfolio de preuves avant/après ──────────────────────────
-- Table : portfolio_items (pas dans schema_updated.sql)

CREATE TABLE IF NOT EXISTS portfolio_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id BIGINT       NOT NULL,
  label         VARCHAR(200) NOT NULL DEFAULT '',
  before_url    VARCHAR(500) NULL,
  after_url     VARCHAR(500) NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_portfolio_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_portfolio_technician ON portfolio_items (technician_id);


-- ─── Migration : table des refus de demandes ────────────────────────────────
-- Table : request_declines (pas dans schema_updated.sql)

CREATE TABLE IF NOT EXISTS request_declines (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    BIGINT    NOT NULL,
  technician_id BIGINT    NOT NULL,
  reason        VARCHAR(20) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_request_decline UNIQUE (request_id, technician_id),
  CONSTRAINT fk_request_declines_request    FOREIGN KEY (request_id)    REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_request_declines_technician FOREIGN KEY (technician_id) REFERENCES technicians (id)    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_request_declines_technician ON request_declines (technician_id);


-- ─── Migration : retraits (withdrawals) ────────────────────────────────────
-- Table : withdrawals (pas dans schema_updated.sql)
-- Inclut déjà le modèle final avec client_user_id et technician_user_id nullable.

CREATE TABLE IF NOT EXISTS withdrawals (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_user_id  BIGINT       NULL,
  client_user_id      BIGINT       NULL,
  amount              DECIMAL(12,2) NOT NULL,
  method              VARCHAR(20)  NOT NULL DEFAULT 'momo',
  account             VARCHAR(60)  NOT NULL,
  status              VARCHAR(20)  NOT NULL DEFAULT 'pending',
  notes               TEXT         NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_withdrawals_technician FOREIGN KEY (technician_user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_withdrawals_client     FOREIGN KEY (client_user_id)     REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_withdrawals_method CHECK (method IN ('momo','orange','bank')),
  CONSTRAINT chk_withdrawals_status CHECK (status IN ('pending','paid','rejected'))
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_technician ON withdrawals (technician_user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_client     ON withdrawals (client_user_id);


-- ─── Seed : utilisateur système pour messages de chat ────────────────────────
-- Utilisateur requis pour les messages système du chat
-- (acceptation/refus de devis et de planification).

INSERT INTO users (id, username, email, password_hash, first_name, last_name, role, status)
VALUES (999999999999, 'system', 'system@mboatech.com', '', 'MboaTech', 'Systeme', 'client', 'active')
ON CONFLICT (id) DO UPDATE SET first_name = EXCLUDED.first_name;
