-- Migration: documents KYC déposés par les utilisateurs
-- (CNI recto/verso, certificat métier, lettres de recommandation).

CREATE TABLE IF NOT EXISTS kyc_documents (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  doc_type   VARCHAR(50)  NOT NULL,
  file_url   VARCHAR(500) NOT NULL,
  status     VARCHAR(20)  NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_kyc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kyc_user ON kyc_documents (user_id);