-- Retraits : paiements sortants de la plateforme vers un technicien ou un client.
--
-- NOTE : cette table est créée directement sous SON MODÈLE FINAL (client_user_id
-- inclus, technician_user_id nullable) pour qu'une installation neuve (--fresh)
-- soit cohérente malgré le classement alphabétique des migrations
-- (migration_2026_08_add_client_withdrawals.sql s'exécute AVANT ce fichier et
-- est un no-op sur base neuve). Sur une base existante, cette migration ne
-- recrée pas la table (CREATE TABLE IF NOT EXISTS) ; la mise à jour des tables
-- déjà présentes est gérée par add_client_withdrawals.

CREATE TABLE IF NOT EXISTS withdrawals (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_user_id  BIGINT       NULL,
  client_user_id      BIGINT       NULL,
  amount              DECIMAL(12,2) NOT NULL,
  method              VARCHAR(20)  NOT NULL DEFAULT 'momo',
  account             VARCHAR(60)  NOT NULL,
  status              VARCHAR(20)  NOT NULL DEFAULT 'pending',
  notes               TEXT         NULL,
  created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_withdrawals_technician FOREIGN KEY (technician_user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_withdrawals_client     FOREIGN KEY (client_user_id)     REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_withdrawals_method CHECK (method IN ('momo','orange','bank')),
  CONSTRAINT chk_withdrawals_status CHECK (status IN ('pending','paid','rejected'))
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_technician ON withdrawals (technician_user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_client     ON withdrawals (client_user_id);