-- Migration: persistance des notifications pour que les utilisateurs les
-- voient après rechargement ou connexion ultérieure. Les broadcasts SSE
-- restent pour le temps réel ; cette table est la source de vérité de la
-- cloche de notification.

CREATE TABLE IF NOT EXISTS notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  title      VARCHAR(200) NOT NULL,
  message    TEXT         NULL,
  type       VARCHAR(20)  NOT NULL DEFAULT 'system',
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, is_read);