-- Migration: portfolio de preuves avant/après (réalisations) ajoutées par les techniciens.

CREATE TABLE IF NOT EXISTS portfolio_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id BIGINT       NOT NULL,
  label         VARCHAR(200) NOT NULL DEFAULT '',
  before_url    VARCHAR(500) NULL,
  after_url     VARCHAR(500) NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_portfolio_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_portfolio_technician ON portfolio_items (technician_id);