-- Migration: attestations table
-- Système d'attestation de service pour les techniciens

DO $$ BEGIN
  CREATE TYPE attestation_level AS ENUM ('BRONZE','SILVER','GOLD','DIAMOND');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS attestations (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id      BIGINT            NOT NULL,
  intervention_count INT               NOT NULL,
  avg_rating         DECIMAL(3,1)      NOT NULL,
  level              attestation_level NOT NULL,
  attestation_number VARCHAR(30)       NOT NULL,
  generated_at       TIMESTAMP         NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_attestation_number     UNIQUE (attestation_number),
  CONSTRAINT fk_attestation_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_attestation_technician ON attestations (technician_id);