-- ═══════════════════════════════════════════════════════════════════════
-- MboaTech – Migration complète idempotente
-- ═══════════════════════════════════════════════════════════════════════
-- Ce fichier est 100 % idempotent : il peut être exécuté N fois sans
-- effet secondaire. Il crée / complète tout ce qui manque :
--   • tables        (CREATE TABLE IF NOT EXISTS)
--   • colonnes      (ADD COLUMN IF NOT EXISTS)
--   • index         (CREATE INDEX IF NOT EXISTS)
--   • triggers      (DO … EXCEPTION WHEN duplicate_object)
--   • contraintes   (DO … EXCEPTION WHEN duplicate_object)
--   • fonctions     (CREATE OR REPLACE)
--   • données seed  (INSERT … ON CONFLICT DO NOTHING)
-- ═══════════════════════════════════════════════════════════════════════

-- ─── 0. Fonction utilitaire : updated_at ────────────────────────────

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : users                                                   ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  role          VARCHAR(20)  NOT NULL DEFAULT 'client',
  phone         VARCHAR(30)  NULL,
  photo_url     VARCHAR(500) NULL,
  status        VARCHAR(20)  NOT NULL DEFAULT 'active',
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_users_status CHECK (status IN ('active','inactive','pending','suspended')),
  CONSTRAINT chk_users_role   CHECK (role IN ('client','technician','admin'))
);

-- Colonnes pouvant manquer sur une table créée incomplètement
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash  VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name     VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name      VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS role           VARCHAR(20)  NOT NULL DEFAULT 'client';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone          VARCHAR(30)  NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_url      VARCHAR(500) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status         VARCHAR(20)  NOT NULL DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at     TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at     TIMESTAMP    NOT NULL DEFAULT NOW();

-- Contraintes CHECK (ignorées si déjà présentes)
DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT chk_users_status CHECK (status IN ('active','inactive','pending','suspended'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('client','technician','admin'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Trigger updated_at
DO $$ BEGIN
  CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : clients                                                 ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS clients (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  city       VARCHAR(120) NULL,
  location   VARCHAR(255) NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE clients ADD COLUMN IF NOT EXISTS city       VARCHAR(120) NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS location   VARCHAR(255) NULL;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS created_at TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE clients ADD CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TRIGGER set_clients_updated_at
    BEFORE UPDATE ON clients
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : technicians                                             ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS technicians (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               BIGINT              NOT NULL UNIQUE,
  domain                VARCHAR(150)        NULL,
  city                  VARCHAR(120)        NULL,
  location              VARCHAR(255)        NULL,
  bio                   TEXT                NULL,
  specialties           TEXT                NULL,
  rating_avg            DECIMAL(3,2)        NOT NULL DEFAULT 0.00,
  rating_count          INT                 NOT NULL DEFAULT 0,
  experience_years      SMALLINT            NULL,
  verified              BOOLEAN             NOT NULL DEFAULT FALSE,
  availability_status   VARCHAR(20)         NOT NULL DEFAULT 'available',
  hourly_rate           DECIMAL(10,2)       NULL,
  success_rate          DECIMAL(5,2)        NOT NULL DEFAULT 0.00,
  acceptance_count      INT                 NOT NULL DEFAULT 0,
  decline_count         INT                 NOT NULL DEFAULT 0,
  avg_response_time_sec INT                 NOT NULL DEFAULT 0,
  suspended_until       TIMESTAMP           NULL,
  suspended_permanent   BOOLEAN             NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_technician_profiles_availability_status
    CHECK (availability_status IN ('available','busy','offline'))
);

ALTER TABLE technicians ADD COLUMN IF NOT EXISTS domain                VARCHAR(150)  NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS city                  VARCHAR(120)  NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS location              VARCHAR(255)  NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS bio                   TEXT          NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS specialties           TEXT          NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS rating_avg            DECIMAL(3,2)  NOT NULL DEFAULT 0.00;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS rating_count          INT           NOT NULL DEFAULT 0;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS experience_years      SMALLINT      NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS verified              BOOLEAN       NOT NULL DEFAULT FALSE;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS availability_status   VARCHAR(20)   NOT NULL DEFAULT 'available';
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS hourly_rate           DECIMAL(10,2) NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS success_rate          DECIMAL(5,2)  NOT NULL DEFAULT 0.00;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS acceptance_count      INT           NOT NULL DEFAULT 0;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS decline_count         INT           NOT NULL DEFAULT 0;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS avg_response_time_sec INT           NOT NULL DEFAULT 0;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS suspended_until       TIMESTAMP     NULL;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS suspended_permanent   BOOLEAN       NOT NULL DEFAULT FALSE;
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS created_at            TIMESTAMP     NOT NULL DEFAULT NOW();
ALTER TABLE technicians ADD COLUMN IF NOT EXISTS updated_at            TIMESTAMP     NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE technicians ADD CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE technicians ADD CONSTRAINT chk_technician_profiles_availability_status
    CHECK (availability_status IN ('available','busy','offline'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TRIGGER set_technicians_updated_at
    BEFORE UPDATE ON technicians
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : admins                                                  ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS admins (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  role_name  VARCHAR(50)  NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE admins ADD COLUMN IF NOT EXISTS role_name  VARCHAR(50)  NOT NULL DEFAULT 'admin';
ALTER TABLE admins ADD COLUMN IF NOT EXISTS created_at TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE admins ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE admins ADD CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TRIGGER set_admins_updated_at
    BEFORE UPDATE ON admins
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : service_requests                                        ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS service_requests (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id               BIGINT       NOT NULL,
  technician_id           BIGINT       NULL,
  category                VARCHAR(100) NOT NULL,
  description             TEXT         NOT NULL,
  urgency                 VARCHAR(20)  NOT NULL DEFAULT 'normal',
  status                  VARCHAR(20)  NOT NULL DEFAULT 'published',
  budget_min              DECIMAL(10,2) NULL,
  budget_max              DECIMAL(10,2) NULL,
  address                 VARCHAR(255) NULL,
  city                    VARCHAR(120) NULL,
  scheduled_at            TIMESTAMP    NULL,
  reserved_until          TIMESTAMP    NULL,
  completed_at            TIMESTAMP    NULL,
  funds_deposited         BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_open            BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_reporter_user_id BIGINT      NULL,
  dispute_open_at         TIMESTAMP    NULL,
  created_at              TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_service_requests_client     FOREIGN KEY (client_id)     REFERENCES clients (id)     ON DELETE CASCADE,
  CONSTRAINT fk_service_requests_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE SET NULL,
  CONSTRAINT chk_service_requests_urgency CHECK (urgency IN ('normal','important','critique')),
  CONSTRAINT chk_service_requests_status   CHECK (status IN ('draft','published','assigned','in_progress','completed','cancelled','disputed'))
);

ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS client_id               BIGINT       NOT NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS technician_id           BIGINT       NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS category                VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS description             TEXT         NOT NULL DEFAULT '';
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS urgency                 VARCHAR(20)  NOT NULL DEFAULT 'normal';
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS status                  VARCHAR(20)  NOT NULL DEFAULT 'published';
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS budget_min              DECIMAL(10,2) NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS budget_max              DECIMAL(10,2) NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS address                 VARCHAR(255) NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS city                    VARCHAR(120) NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS scheduled_at            TIMESTAMP    NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS reserved_until          TIMESTAMP    NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS completed_at            TIMESTAMP    NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS funds_deposited         BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS dispute_open            BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS dispute_reporter_user_id BIGINT      NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS dispute_open_at         TIMESTAMP    NULL;
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS created_at              TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS updated_at              TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE service_requests ADD CONSTRAINT fk_service_requests_client
    FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE service_requests ADD CONSTRAINT fk_service_requests_technician
    FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE service_requests ADD CONSTRAINT chk_service_requests_urgency
    CHECK (urgency IN ('normal','important','critique'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE service_requests ADD CONSTRAINT chk_service_requests_status
    CHECK (status IN ('draft','published','assigned','in_progress','completed','cancelled','disputed'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_service_requests_client     ON service_requests (client_id);
CREATE INDEX IF NOT EXISTS idx_service_requests_technician ON service_requests (technician_id);

DO $$ BEGIN
  CREATE TRIGGER set_service_requests_updated_at
    BEFORE UPDATE ON service_requests
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : chat_messages                                           ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS chat_messages (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  sender_user_id     BIGINT       NOT NULL,
  message_text       TEXT         NULL,
  attachment_url     VARCHAR(500) NULL,
  is_read            BOOLEAN      NOT NULL DEFAULT FALSE,
  schedule_at        TIMESTAMP    NULL,
  schedule_status    VARCHAR(20)  NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chat_messages_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_messages_sender  FOREIGN KEY (sender_user_id)     REFERENCES users (id)          ON DELETE CASCADE
);

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS service_request_id BIGINT       NOT NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS sender_user_id     BIGINT       NOT NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS message_text       TEXT         NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS attachment_url     VARCHAR(500) NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS is_read            BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS schedule_at        TIMESTAMP    NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS schedule_status    VARCHAR(20)  NULL;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_at         TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_request
    FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_sender
    FOREIGN KEY (sender_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_chat_service_request ON chat_messages (service_request_id);
CREATE INDEX IF NOT EXISTS idx_chat_sender          ON chat_messages (sender_user_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : payments                                                ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT        NOT NULL,
  payer_user_id      BIGINT        NOT NULL,
  payee_user_id      BIGINT        NOT NULL,
  amount             DECIMAL(12,2) NOT NULL,
  currency           VARCHAR(10)   NOT NULL DEFAULT 'XAF',
  status             VARCHAR(20)   NOT NULL DEFAULT 'pending',
  method             VARCHAR(50)   NOT NULL DEFAULT 'momo',
  transaction_ref    VARCHAR(255)  NULL,
  payment_url        VARCHAR(500)  NULL,
  notes              TEXT          NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_payments_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_payer   FOREIGN KEY (payer_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT fk_payments_payee   FOREIGN KEY (payee_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_payments_status CHECK (status IN ('pending','held','released','refunded','failed'))
);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS service_request_id BIGINT        NOT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_user_id      BIGINT        NOT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payee_user_id      BIGINT        NOT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount             DECIMAL(12,2) NOT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency           VARCHAR(10)   NOT NULL DEFAULT 'XAF';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status             VARCHAR(20)   NOT NULL DEFAULT 'pending';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method             VARCHAR(50)   NOT NULL DEFAULT 'momo';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_ref    VARCHAR(255)  NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_url        VARCHAR(500)  NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS notes              TEXT          NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at         TIMESTAMP     NOT NULL DEFAULT NOW();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at         TIMESTAMP     NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE payments ADD CONSTRAINT fk_payments_request
    FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE payments ADD CONSTRAINT fk_payments_payer
    FOREIGN KEY (payer_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE payments ADD CONSTRAINT fk_payments_payee
    FOREIGN KEY (payee_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE payments ADD CONSTRAINT chk_payments_status
    CHECK (status IN ('pending','held','released','refunded','failed'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_payments_request ON payments (service_request_id);

DO $$ BEGIN
  CREATE TRIGGER set_payments_updated_at
    BEFORE UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : technician_recommendations                              ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS technician_recommendations (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id       BIGINT       NOT NULL,
  recommender_user_id BIGINT       NULL,
  recommender_name    VARCHAR(150) NULL,
  comment             TEXT         NULL,
  rating              SMALLINT     NULL,
  verified            BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_recommendations_technician  FOREIGN KEY (technician_id)       REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT fk_recommendations_recommender FOREIGN KEY (recommender_user_id) REFERENCES users (id)      ON DELETE SET NULL
);

ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS technician_id       BIGINT       NOT NULL;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS recommender_user_id BIGINT       NULL;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS recommender_name    VARCHAR(150) NULL;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS comment             TEXT         NULL;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS rating              SMALLINT     NULL;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS verified            BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE technician_recommendations ADD COLUMN IF NOT EXISTS created_at          TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE technician_recommendations ADD CONSTRAINT fk_recommendations_technician
    FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE technician_recommendations ADD CONSTRAINT fk_recommendations_recommender
    FOREIGN KEY (recommender_user_id) REFERENCES users (id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_recommendations_technician ON technician_recommendations (technician_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : notifications                                           ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  title      VARCHAR(200) NOT NULL,
  message    TEXT         NULL,
  type       VARCHAR(20)  NOT NULL DEFAULT 'system',
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS user_id    BIGINT       NOT NULL;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title      VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS message    TEXT         NULL;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS type       VARCHAR(20)  NOT NULL DEFAULT 'system';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read    BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, is_read);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : documents (KYC)                                         ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS documents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT       NOT NULL,
  type            VARCHAR(30)  NOT NULL DEFAULT 'other',
  file_url        VARCHAR(500) NOT NULL,
  status          VARCHAR(20)  NOT NULL DEFAULT 'pending',
  review_comments TEXT         NULL,
  uploaded_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
  reviewed_at     TIMESTAMP    NULL,
  CONSTRAINT fk_documents_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_documents_type   CHECK (type   IN ('id_card','recommendation_letter','certification','other')),
  CONSTRAINT chk_documents_status CHECK (status IN ('pending','approved','rejected'))
);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS user_id         BIGINT       NOT NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS type            VARCHAR(30)  NOT NULL DEFAULT 'other';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_url        VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS status          VARCHAR(20)  NOT NULL DEFAULT 'pending';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS review_comments TEXT         NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS uploaded_at     TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE documents ADD COLUMN IF NOT EXISTS reviewed_at     TIMESTAMP    NULL;

DO $$ BEGIN
  ALTER TABLE documents ADD CONSTRAINT fk_documents_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE documents ADD CONSTRAINT chk_documents_type
    CHECK (type IN ('id_card','recommendation_letter','certification','other'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE documents ADD CONSTRAINT chk_documents_status
    CHECK (status IN ('pending','approved','rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_documents_user ON documents (user_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : kyc_documents                                           ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS kyc_documents (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  doc_type   VARCHAR(50)  NOT NULL,
  file_url   VARCHAR(500) NOT NULL,
  status     VARCHAR(20)  NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_kyc_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS user_id    BIGINT       NOT NULL;
ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS doc_type   VARCHAR(50)  NOT NULL DEFAULT '';
ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS file_url   VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS status     VARCHAR(20)  NOT NULL DEFAULT 'pending';
ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS created_at TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE kyc_documents ADD CONSTRAINT fk_kyc_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_kyc_user ON kyc_documents (user_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : disputes                                                ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS disputes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  reported_by_user_id BIGINT      NOT NULL,
  description        TEXT         NOT NULL,
  status             VARCHAR(20)  NOT NULL DEFAULT 'open',
  resolution         TEXT         NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  resolved_at        TIMESTAMP    NULL,
  CONSTRAINT fk_disputes_request     FOREIGN KEY (service_request_id)   REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_disputes_reported_by FOREIGN KEY (reported_by_user_id)  REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_disputes_status CHECK (status IN ('open','under_review','resolved','rejected'))
);

ALTER TABLE disputes ADD COLUMN IF NOT EXISTS service_request_id  BIGINT       NOT NULL;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS reported_by_user_id BIGINT       NOT NULL;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS description         TEXT         NOT NULL DEFAULT '';
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS status              VARCHAR(20)  NOT NULL DEFAULT 'open';
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS resolution          TEXT         NULL;
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS created_at          TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE disputes ADD COLUMN IF NOT EXISTS resolved_at         TIMESTAMP    NULL;

DO $$ BEGIN
  ALTER TABLE disputes ADD CONSTRAINT fk_disputes_request
    FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE disputes ADD CONSTRAINT fk_disputes_reported_by
    FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE disputes ADD CONSTRAINT chk_disputes_status
    CHECK (status IN ('open','under_review','resolved','rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_disputes_request ON disputes (service_request_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : attestations                                            ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS attestations (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id      BIGINT        NOT NULL,
  intervention_count INT           NOT NULL,
  avg_rating         DECIMAL(3,1)  NOT NULL,
  level              VARCHAR(20)   NOT NULL,
  attestation_number VARCHAR(30)   NOT NULL,
  generated_at       TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_attestation_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT uk_attestation_number     UNIQUE (attestation_number),
  CONSTRAINT chk_attestations_level
    CHECK (level IN ('BRONZE','SILVER','GOLD','DIAMOND'))
);

ALTER TABLE attestations ADD COLUMN IF NOT EXISTS technician_id      BIGINT       NOT NULL;
ALTER TABLE attestations ADD COLUMN IF NOT EXISTS intervention_count INT          NOT NULL DEFAULT 0;
ALTER TABLE attestations ADD COLUMN IF NOT EXISTS avg_rating         DECIMAL(3,1) NOT NULL DEFAULT 0.0;
ALTER TABLE attestations ADD COLUMN IF NOT EXISTS level              VARCHAR(20)  NOT NULL DEFAULT 'BRONZE';
ALTER TABLE attestations ADD COLUMN IF NOT EXISTS attestation_number VARCHAR(30)  NOT NULL DEFAULT '';
ALTER TABLE attestations ADD COLUMN IF NOT EXISTS generated_at       TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE attestations ADD CONSTRAINT fk_attestation_technician
    FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE attestations ADD CONSTRAINT chk_attestations_level
    CHECK (level IN ('BRONZE','SILVER','GOLD','DIAMOND'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_attestation_technician ON attestations (technician_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : auth_sessions                                           ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS auth_sessions (
  token      VARCHAR(64)  NOT NULL PRIMARY KEY,
  username   VARCHAR(255) NOT NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP    NOT NULL DEFAULT (NOW() + INTERVAL '30 days')
);

ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS username   VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP    NOT NULL DEFAULT NOW();
ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP    NOT NULL DEFAULT (NOW() + INTERVAL '30 days');

CREATE INDEX IF NOT EXISTS idx_auth_sessions_username ON auth_sessions (username);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : withdrawals                                             ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS withdrawals (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_user_id  BIGINT        NULL,
  client_user_id      BIGINT        NULL,
  amount              DECIMAL(12,2) NOT NULL,
  method              VARCHAR(20)   NOT NULL DEFAULT 'momo',
  account             VARCHAR(60)   NOT NULL,
  status              VARCHAR(20)   NOT NULL DEFAULT 'pending',
  notes               TEXT          NULL,
  created_at          TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_withdrawals_technician FOREIGN KEY (technician_user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_withdrawals_client     FOREIGN KEY (client_user_id)     REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_withdrawals_method CHECK (method IN ('momo','orange','bank')),
  CONSTRAINT chk_withdrawals_status CHECK (status IN ('pending','paid','rejected'))
);

ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS technician_user_id BIGINT        NULL;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS client_user_id     BIGINT        NULL;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS amount             DECIMAL(12,2) NOT NULL;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS method             VARCHAR(20)   NOT NULL DEFAULT 'momo';
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS account            VARCHAR(60)   NOT NULL DEFAULT '';
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS status             VARCHAR(20)   NOT NULL DEFAULT 'pending';
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS notes              TEXT          NULL;
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS created_at         TIMESTAMP     NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE withdrawals ADD CONSTRAINT fk_withdrawals_technician
    FOREIGN KEY (technician_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE withdrawals ADD CONSTRAINT fk_withdrawals_client
    FOREIGN KEY (client_user_id) REFERENCES users (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE withdrawals ADD CONSTRAINT chk_withdrawals_method
    CHECK (method IN ('momo','orange','bank'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE withdrawals ADD CONSTRAINT chk_withdrawals_status
    CHECK (status IN ('pending','paid','rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_withdrawals_technician ON withdrawals (technician_user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_client     ON withdrawals (client_user_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : request_declines                                        ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS request_declines (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    BIGINT       NOT NULL,
  technician_id BIGINT       NOT NULL,
  reason        VARCHAR(20)  NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_request_decline UNIQUE (request_id, technician_id),
  CONSTRAINT fk_request_declines_request    FOREIGN KEY (request_id)    REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_request_declines_technician FOREIGN KEY (technician_id) REFERENCES technicians (id)    ON DELETE CASCADE
);

ALTER TABLE request_declines ADD COLUMN IF NOT EXISTS request_id    BIGINT      NOT NULL;
ALTER TABLE request_declines ADD COLUMN IF NOT EXISTS technician_id BIGINT      NOT NULL;
ALTER TABLE request_declines ADD COLUMN IF NOT EXISTS reason        VARCHAR(20) NULL;
ALTER TABLE request_declines ADD COLUMN IF NOT EXISTS created_at    TIMESTAMP   NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE request_declines ADD CONSTRAINT fk_request_declines_request
    FOREIGN KEY (request_id) REFERENCES service_requests (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE request_declines ADD CONSTRAINT fk_request_declines_technician
    FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_request_declines_technician ON request_declines (technician_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : portfolio_items                                         ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS portfolio_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id BIGINT       NOT NULL,
  label         VARCHAR(200) NOT NULL DEFAULT '',
  before_url    VARCHAR(500) NULL,
  after_url     VARCHAR(500) NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_portfolio_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE
);

ALTER TABLE portfolio_items ADD COLUMN IF NOT EXISTS technician_id BIGINT       NOT NULL;
ALTER TABLE portfolio_items ADD COLUMN IF NOT EXISTS label         VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE portfolio_items ADD COLUMN IF NOT EXISTS before_url    VARCHAR(500) NULL;
ALTER TABLE portfolio_items ADD COLUMN IF NOT EXISTS after_url     VARCHAR(500) NULL;
ALTER TABLE portfolio_items ADD COLUMN IF NOT EXISTS created_at    TIMESTAMP    NOT NULL DEFAULT NOW();

DO $$ BEGIN
  ALTER TABLE portfolio_items ADD CONSTRAINT fk_portfolio_technician
    FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_portfolio_technician ON portfolio_items (technician_id);


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  TABLE : platform_settings                                       ║
-- ╚═══════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS platform_settings (
  setting_key   VARCHAR(64)  NOT NULL PRIMARY KEY,
  setting_value VARCHAR(255) NOT NULL DEFAULT '',
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS setting_value VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE platform_settings ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMP    NOT NULL DEFAULT NOW();


-- ╔═══════════════════════════════════════════════════════════════════╗
-- ║  DONNÉES SEED                                                    ║
-- ╚═══════════════════════════════════════════════════════════════════╝

-- Utilisateur système (messages automatiques du chat)
INSERT INTO users (id, username, email, password_hash, first_name, last_name, role, status)
VALUES (999999999999, 'system', 'system@mboatech.com', '', 'MboaTech', 'Systeme', 'client', 'active')
ON CONFLICT (id) DO UPDATE
  SET first_name = EXCLUDED.first_name,
      last_name  = EXCLUDED.last_name;

-- Réglage par défaut : paiements activés
INSERT INTO platform_settings (setting_key, setting_value)
VALUES ('payments_enabled', 'true')
ON CONFLICT (setting_key) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════════
-- FIN – Cette migration est 100 % idempotente et peut être relancée
--       à tout moment sans risque.
-- ═══════════════════════════════════════════════════════════════════════
