-- Table des refus de demandes par les techniciens (anti-accaparement).

CREATE TABLE IF NOT EXISTS request_declines (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id    BIGINT    NOT NULL,
  technician_id BIGINT    NOT NULL,
  reason        VARCHAR(20) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_request_decline UNIQUE (request_id, technician_id),
  CONSTRAINT fk_request_declines_request    FOREIGN KEY (request_id)    REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_request_declines_technician FOREIGN KEY (technician_id) REFERENCES technicians (id)    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_request_declines_technician ON request_declines (technician_id);