-- PostgreSQL schema for MboaTech (VARIANTE ORIGINALE, DÉPRÉCIÉE)
--
-- ⚠️  Ce fichier reflète l'ancien schéma initial (technician_profiles, etc.).
--     Le schéma canonique et à jour est db/schema_updated.sql : utilisez-le,
--     puis appliquez les migrations via ./deploy/migrate-db.sh --fresh.
--     Ce fichier n'est conservé qu'à titre historique et SANS garantie d'être
--     conforme au modèle JPA actuel.

-- Types ENUM (compatibles avec la variante originale).
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('client','technician','admin','support');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE user_status AS ENUM ('active','inactive','pending','suspended');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE availability_status AS ENUM ('available','busy','offline');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Trigger pour reproduire ON UPDATE CURRENT_TIMESTAMP.
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)   NOT NULL UNIQUE,
  email         VARCHAR(255)  NOT NULL UNIQUE,
  password_hash VARCHAR(255)  NOT NULL,
  first_name    VARCHAR(100)  NOT NULL,
  last_name     VARCHAR(100)  NOT NULL,
  role          user_role     NOT NULL DEFAULT 'client',
  domain        VARCHAR(150)  NULL,
  city          VARCHAR(120)  NULL,
  location      VARCHAR(255)  NULL,
  phone         VARCHAR(30)   NULL,
  status        user_status   NOT NULL DEFAULT 'active',
  created_at    TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS technician_profiles (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              BIGINT              NOT NULL UNIQUE,
  bio                  TEXT                NULL,
  specialties          TEXT                NULL,
  rating_avg           DECIMAL(3,2)        NOT NULL DEFAULT 0.00,
  rating_count         INT                 NOT NULL DEFAULT 0,
  experience_years     SMALLINT            NULL,
  hourly_rate          DECIMAL(10,2)       NULL,
  verified             BOOLEAN             NOT NULL DEFAULT FALSE,
  availability_status  availability_status NOT NULL DEFAULT 'available',
  photo_url            VARCHAR(500)        NULL,
  success_rate         DECIMAL(5,2)        NOT NULL DEFAULT 0.00,
  avg_response_time_sec INT                NOT NULL DEFAULT 0,
  created_at           TIMESTAMP           NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMP           NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_technician_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER set_technician_profiles_updated_at
  BEFORE UPDATE ON technician_profiles
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS service_requests (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id          BIGINT        NOT NULL,
  technician_id      BIGINT        NULL,
  category           VARCHAR(100)  NOT NULL,
  description        TEXT          NOT NULL,
  urgency            VARCHAR(20)   NOT NULL DEFAULT 'normal',
  status             VARCHAR(20)   NOT NULL DEFAULT 'published',
  budget_min         DECIMAL(10,2) NULL,
  budget_max         DECIMAL(10,2) NULL,
  address            VARCHAR(255)  NULL,
  city               VARCHAR(120)  NULL,
  scheduled_at       TIMESTAMP     NULL,
  completed_at       TIMESTAMP     NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_service_requests_client     FOREIGN KEY (client_id)     REFERENCES users (id)      ON DELETE CASCADE,
  CONSTRAINT fk_service_requests_technician FOREIGN KEY (technician_id) REFERENCES users (id)      ON DELETE SET NULL,
  CONSTRAINT chk_service_requests_urgency   CHECK (urgency IN ('normal','important','critique')),
  CONSTRAINT chk_service_requests_status    CHECK (status IN ('draft','published','assigned','in_progress','completed','cancelled','disputed'))
);

CREATE INDEX idx_service_requests_client     ON service_requests (client_id);
CREATE INDEX idx_service_requests_technician ON service_requests (technician_id);

CREATE TRIGGER set_service_requests_updated_at
  BEFORE UPDATE ON service_requests
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS chat_messages (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  sender_id          BIGINT       NOT NULL,
  message_text       TEXT         NULL,
  attachment_url     VARCHAR(500) NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chat_messages_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_messages_sender  FOREIGN KEY (sender_id)          REFERENCES users (id)           ON DELETE CASCADE
);

CREATE INDEX idx_chat_service_request ON chat_messages (service_request_id);
CREATE INDEX idx_chat_sender          ON chat_messages (sender_id);

CREATE TABLE IF NOT EXISTS payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT        NOT NULL,
  payer_id           BIGINT        NOT NULL,
  payee_id           BIGINT        NOT NULL,
  amount             DECIMAL(12,2) NOT NULL,
  currency           VARCHAR(10)   NOT NULL DEFAULT 'XAF',
  status             VARCHAR(20)   NOT NULL DEFAULT 'pending',
  method             VARCHAR(50)   NOT NULL DEFAULT 'momo',
  transaction_ref    VARCHAR(255)  NULL,
  payment_url        VARCHAR(500)  NULL,
  notes              TEXT          NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_payments_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_payer   FOREIGN KEY (payer_id)           REFERENCES users (id)            ON DELETE CASCADE,
  CONSTRAINT fk_payments_payee   FOREIGN KEY (payee_id)           REFERENCES users (id)            ON DELETE CASCADE,
  CONSTRAINT chk_payments_status CHECK (status IN ('pending','held','released','refunded','failed'))
);

CREATE INDEX idx_payments_request ON payments (service_request_id);

CREATE TRIGGER set_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS documents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT       NOT NULL,
  type            VARCHAR(30)  NOT NULL DEFAULT 'other',
  file_url        VARCHAR(500) NOT NULL,
  status          VARCHAR(20)  NOT NULL DEFAULT 'pending',
  review_comments TEXT         NULL,
  uploaded_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
  reviewed_at     TIMESTAMP    NULL,
  CONSTRAINT fk_documents_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_documents_type   CHECK (type   IN ('id_card','recommendation_letter','certification','other')),
  CONSTRAINT chk_documents_status CHECK (status IN ('pending','approved','rejected'))
);

CREATE INDEX idx_documents_user ON documents (user_id);

CREATE TABLE IF NOT EXISTS disputes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  reported_by        BIGINT       NOT NULL,
  description        TEXT         NOT NULL,
  status             VARCHAR(20)  NOT NULL DEFAULT 'open',
  resolution         TEXT         NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  resolved_at        TIMESTAMP    NULL,
  CONSTRAINT fk_disputes_request    FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_disputes_reported_by FOREIGN KEY (reported_by)       REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_disputes_status CHECK (status IN ('open','under_review','resolved','rejected'))
);

CREATE INDEX idx_disputes_request ON disputes (service_request_id);