-- PostgreSQL schema for MboaTech
-- Converted from MySQL 8.0
--
-- Note : role / availability_status / level sont mappés en Java par
-- @Enumerated(EnumType.STRING) (enums Role / AvailabilityStatus /
-- AttestationLevel). Ils sont donc stockés en VARCHAR + contrainte CHECK :
-- PostgreSQL ne permet pas de comparer implicitement un VARCHAR à un type
-- ENUM natif sous Hibernate. Les autres colonnes « enum » MySQL sont aussi
-- mappées en String Java (VARCHAR + CHECK).

-- ─── Trigger function for updated_at ────────────────────────────────

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─── Tables ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL UNIQUE,
  email         VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  role          VARCHAR(20)  NOT NULL DEFAULT 'client',
  phone         VARCHAR(30)  NULL,
  photo_url     VARCHAR(500) NULL,
  status        VARCHAR(20)  NOT NULL DEFAULT 'active',
  created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_users_status CHECK (status IN ('active','inactive','pending','suspended')),
  CONSTRAINT chk_users_role   CHECK (role IN ('client','technician','admin'))
);

CREATE TRIGGER set_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS clients (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  city       VARCHAR(120) NULL,
  location   VARCHAR(255) NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER set_clients_updated_at
  BEFORE UPDATE ON clients
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS technicians (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               BIGINT              NOT NULL UNIQUE,
  domain                VARCHAR(150)        NULL,
  city                  VARCHAR(120)        NULL,
  location              VARCHAR(255)        NULL,
  bio                   TEXT                NULL,
  specialties           TEXT                NULL,
  rating_avg            DECIMAL(3,2)        NOT NULL DEFAULT 0.00,
  rating_count          INT                 NOT NULL DEFAULT 0,
  experience_years      SMALLINT            NULL,
  verified              BOOLEAN             NOT NULL DEFAULT FALSE,
  availability_status   VARCHAR(20) NOT NULL DEFAULT 'available',
  hourly_rate           DECIMAL(10,2)       NULL,
  success_rate          DECIMAL(5,2)        NOT NULL DEFAULT 0.00,
  acceptance_count      INT                 NOT NULL DEFAULT 0,
  decline_count         INT                 NOT NULL DEFAULT 0,
  avg_response_time_sec INT                 NOT NULL DEFAULT 0,
  suspended_until       TIMESTAMP           NULL,
  suspended_permanent   BOOLEAN             NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMP           NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_technicians_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_technician_profiles_availability_status
    CHECK (availability_status IN ('available','busy','offline'))
);

CREATE TRIGGER set_technicians_updated_at
  BEFORE UPDATE ON technicians
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS admins (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL UNIQUE,
  role_name  VARCHAR(50)  NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_admins_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER set_admins_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS service_requests (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        BIGINT       NOT NULL,
  technician_id    BIGINT       NULL,
  category         VARCHAR(100) NOT NULL,
  description      TEXT         NOT NULL,
  urgency          VARCHAR(20)  NOT NULL DEFAULT 'normal',
  status           VARCHAR(20)  NOT NULL DEFAULT 'published',
  budget_min       DECIMAL(10,2) NULL,
  budget_max       DECIMAL(10,2) NULL,
  address          VARCHAR(255) NULL,
  city             VARCHAR(120) NULL,
  scheduled_at     TIMESTAMP    NULL,
  reserved_until   TIMESTAMP    NULL,
  completed_at     TIMESTAMP    NULL,
  funds_deposited  BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_open     BOOLEAN      NOT NULL DEFAULT FALSE,
  dispute_reporter_user_id BIGINT NULL,
  dispute_open_at  TIMESTAMP    NULL,
  created_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_service_requests_client     FOREIGN KEY (client_id)     REFERENCES clients (id)     ON DELETE CASCADE,
  CONSTRAINT fk_service_requests_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE SET NULL,
  CONSTRAINT chk_service_requests_urgency CHECK (urgency IN ('normal','important','critique')),
  CONSTRAINT chk_service_requests_status   CHECK (status IN ('draft','published','assigned','in_progress','completed','cancelled','disputed'))
);

CREATE INDEX idx_service_requests_client     ON service_requests (client_id);
CREATE INDEX idx_service_requests_technician ON service_requests (technician_id);

CREATE TRIGGER set_service_requests_updated_at
  BEFORE UPDATE ON service_requests
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS chat_messages (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  sender_user_id     BIGINT       NOT NULL,
  message_text       TEXT         NULL,
  attachment_url     VARCHAR(500) NULL,
  is_read            BOOLEAN      NOT NULL DEFAULT FALSE,
  schedule_at        TIMESTAMP    NULL,
  schedule_status    VARCHAR(20)  NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_chat_messages_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_messages_sender  FOREIGN KEY (sender_user_id)     REFERENCES users (id)          ON DELETE CASCADE
);

CREATE INDEX idx_chat_service_request ON chat_messages (service_request_id);
CREATE INDEX idx_chat_sender          ON chat_messages (sender_user_id);

CREATE TABLE IF NOT EXISTS payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT        NOT NULL,
  payer_user_id      BIGINT        NOT NULL,
  payee_user_id      BIGINT        NOT NULL,
  amount             DECIMAL(12,2) NOT NULL,
  currency           VARCHAR(10)   NOT NULL DEFAULT 'XAF',
  status             VARCHAR(20)   NOT NULL DEFAULT 'pending',
  method             VARCHAR(50)   NOT NULL DEFAULT 'momo',
  transaction_ref    VARCHAR(255)  NULL,
  payment_url        VARCHAR(500)  NULL,
  notes              TEXT          NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP     NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_payments_request FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_payer   FOREIGN KEY (payer_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT fk_payments_payee   FOREIGN KEY (payee_user_id)      REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_payments_status CHECK (status IN ('pending','held','released','refunded','failed'))
);

CREATE INDEX idx_payments_request ON payments (service_request_id);

CREATE TRIGGER set_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TABLE IF NOT EXISTS technician_recommendations (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id       BIGINT       NOT NULL,
  recommender_user_id BIGINT       NULL,
  recommender_name    VARCHAR(150) NULL,
  comment             TEXT         NULL,
  rating              SMALLINT     NULL,
  verified            BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_recommendations_technician  FOREIGN KEY (technician_id)       REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT fk_recommendations_recommender FOREIGN KEY (recommender_user_id) REFERENCES users (id)      ON DELETE SET NULL
);

CREATE INDEX idx_recommendations_technician ON technician_recommendations (technician_id);

CREATE TABLE IF NOT EXISTS notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  title      VARCHAR(200) NOT NULL,
  message    TEXT         NULL,
  type       VARCHAR(20)  NOT NULL DEFAULT 'system',
  is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_user ON notifications (user_id, is_read);

CREATE TABLE IF NOT EXISTS documents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT       NOT NULL,
  type            VARCHAR(30)  NOT NULL DEFAULT 'other',
  file_url        VARCHAR(500) NOT NULL,
  status          VARCHAR(20)  NOT NULL DEFAULT 'pending',
  review_comments TEXT         NULL,
  uploaded_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
  reviewed_at     TIMESTAMP    NULL,
  CONSTRAINT fk_documents_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_documents_type   CHECK (type   IN ('id_card','recommendation_letter','certification','other')),
  CONSTRAINT chk_documents_status CHECK (status IN ('pending','approved','rejected'))
);

CREATE INDEX idx_documents_user ON documents (user_id);

CREATE TABLE IF NOT EXISTS disputes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_request_id BIGINT       NOT NULL,
  reported_by_user_id BIGINT      NOT NULL,
  description        TEXT         NOT NULL,
  status             VARCHAR(20)  NOT NULL DEFAULT 'open',
  resolution         TEXT         NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
  resolved_at        TIMESTAMP    NULL,
  CONSTRAINT fk_disputes_request     FOREIGN KEY (service_request_id)   REFERENCES service_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_disputes_reported_by FOREIGN KEY (reported_by_user_id)  REFERENCES users (id)           ON DELETE CASCADE,
  CONSTRAINT chk_disputes_status CHECK (status IN ('open','under_review','resolved','rejected'))
);

CREATE INDEX idx_disputes_request ON disputes (service_request_id);

CREATE TABLE IF NOT EXISTS attestations (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  technician_id      BIGINT             NOT NULL,
  intervention_count INT                NOT NULL,
  avg_rating         DECIMAL(3,1)       NOT NULL,
  level              VARCHAR(20)      NOT NULL,
  attestation_number VARCHAR(30)        NOT NULL,
  generated_at       TIMESTAMP          NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_attestation_technician FOREIGN KEY (technician_id) REFERENCES technicians (id) ON DELETE CASCADE,
  CONSTRAINT uk_attestation_number     UNIQUE (attestation_number),
  CONSTRAINT chk_attestations_level
    CHECK (level IN ('BRONZE','SILVER','GOLD','DIAMOND'))
);

CREATE INDEX idx_attestation_technician ON attestations (technician_id);